### ISSUE TITLE
Unable to find consistent max/min

### ISSUE THREAD

**Issue by RylanYancey** [gp-97/perlin2d#1]
Hello,

I am trying to use perlin2d to generate noisemaps.

I want specific values in the noisemap to correlate with specific outcomes. 

However, I am unable to establish a consistent range across the noisemap. 

On a small scale, (500x500 sample size), I achieved a max/min of -12/10

On a larger scale, (5000x5000) I achieved a max/min of 29/-20

What is the max/min this function outputs?

**Comment by gecgel** [comment]
I believe the noise range is bias+amplitude*[0,1]. Thus amplitude should be set to (max-min) and the bias should be set to (min). Then, the noise output would be in range [min, max].
